name: Deploy SMPLFY Core Plugin via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ftp.sblik.com
          port: 21
          protocol: ftp
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./smplfy-core/
          server-dir: /public_html/wp-content/plugins/smplfy-core-plugin/
          dry-run: false      # <â€“ optional but recommended
